from pathlib import Path

from jinja2 import Environment, FileSystemLoader, Template
from pydantic import BaseModel, Field


class Decisions(BaseModel):
    import_path: str = Field(
        description="The import path for the decisions class (e.g. com.example.MyDecisions)."
    )


class Class(BaseModel):
    import_path: str = Field(
        description="The import path for the class (e.g. com.example.MyClass)."
    )
    class_name: str = Field(description="The name of the class (e.g. MyClass).")
    instance_name: str = Field(
        description="The name of the instance of the class used in the transformation (e.g. myClass)."
    )


class InitiationDialogue(BaseModel):
    set_configuration: str = Field(
        description="The implementation to set the configuration for the initiation dialogue. This uses the configuration class generated by the decisions class."
    )
    initiate_dialogue: str = Field(
        description="The implementation to initiate the dialogue. This should return an instance of the dialogue class generated by the decisions class."
    )


class TransformationImplementation(Class):
    decisions: Decisions = Field(
        description="The decisions class details for the transformation implementation."
    )
    initiation_dialogue: InitiationDialogue = Field(
        description="The initiation dialogue details for the transformation implementation."
    )
    perform_and_propagate_target_edit: str = Field(
        description="The implementation of the performAndPropagateTargetEdit method."
    )
    perform_and_propagate_source_edit: str = Field(
        description="The implementation of the performAndPropagateSourceEdit method."
    )
    perform_and_propagate_concurrent_edit: str = Field(
        description="The implementation of the performAndPropagateConcurrentEdit method."
    )


class TransformationModel(BaseModel):
    name: str = Field(description="The name of the model (e.g. Family, Person).")
    factory: Class = Field(description="The factory class details for the model.")
    register: Class = Field(description="The registration class details for the model.")
    comparator: Class = Field(description="The comparator class details for the model.")


class BxToolForEMF(BaseModel):
    transformation_package: str = Field(
        description="The package where the transformation implementation will be generated."
    )
    transformation_implementation: TransformationImplementation = Field(
        description="The transformation implementation details."
    )
    source_model: TransformationModel = Field(description="The source model details.")
    target_model: TransformationModel = Field(description="The target model details.")
    additional_imports: list[str] = Field(
        description="Additional imports needed for the transformation implementation in form of a list of strings (e.g. [java.util.ArrayList, java.util.HashMap])."
    )


class BxToolTemplateResolver:
    template: Template

    def __init__(self, template_path: Path = Path.cwd() / "templates"):
        self.template = Environment(
            loader=FileSystemLoader(template_path)
        ).get_template("bxtool.jinja")
        self.raw_template = (template_path / "bxtool.jinja").read_text()

    def get_raw_template(self) -> str:
        return self.raw_template

    def render_template(self, bx_tool_for_emf: BxToolForEMF) -> str:
        return self.template.render(**bx_tool_for_emf.model_dump())
