from pathlib import Path
from typing import TypedDict

from mdeagent.comprehension.plan import TransformationPlan
from mdeagent.evaluation.types import EvaluationRun


class MDEAgentState(TypedDict):
    """
    The State of the MDEAgent. This state contains information and data that is relevant and needed for the entire workflow to function.

    Important! Keep this updated and consistent all the time. This is the state that is passed between the nodes of the workflow, and it is important that all nodes can read and write to this state as needed.
    Important! Only direct nodes are allowed to manipulate this state.

    Example invocation of the MDEAgent workflow:
    ```python
    mdeagent = build_mdeagent(workspace_path=Path("/path/to/workspace")).compile()

    initial_state = MDEAgentState(
        source_model_path=Path("/path/to/source/model"),
        target_model_path=Path("/path/to/target/model"),
        group_id="de.hofuniversity",
        artifact_id="MDEAgentFamilyToPerson",
    )
    mdeagent.ainvoke(initial_state, version="v2")
    """

    # === Workspace ===
    workspace_path: Path                        # This has to be set by the user, and is used to identify the workspace of the workflow.
    source_model_path: Path                     # This has to be set by the user, and is used to identify the source model of the workflow.
    target_model_path: Path                     # This has to be set by the user, and is used to identify the target model of the workflow.

    # === Transformation ===
    transformation_plan: TransformationPlan | None
    transformation_package_path: str  # deprecated

    # === Implementation ===
    group_id: str                               # This has to be set by the user, and is used to identify the group of the generated artifacts.
    artifact_id: str                            # This has to be set by the user, and is used to identify the artifact of the generated artifacts.

    transformation_class_path: Path | None      # This will be generated by the implementation_node and evaluated by the evaluation_node.
    bxtool_path: Path | None                    # This will be generated by the preparation_node and used by the implementation_node.

    # === Evaluation ===
    required_commands: list[str]                # This will be set by the agent at first.
    written_files: list[Path]                   # This will contain the paths of the files that were written by the implementation_node, and can be used by the evaluation_node to evaluate the generated artifacts.
    latest_evaluation_runs: list[EvaluationRun] # This will contain the results of the latest evaluation runs, and can be used by the evaluation_node to evaluate the generated artifacts.

