import shutil
from pathlib import Path

from mdeagent.preparation.maven import MavenProject
from mdeagent.preparation.pom import Dependency, Module, Pom
from mdeagent.preparation.state import ModelImplementation, PreparationState


def read_generated_emf_implementations(
    package_path: Path, artifact_id: str
) -> dict[Path, str]:
    """Reads the generated EMF implementations from the gen folder within the package path.

    EMF-generated model implementations are typically located in a 'gen' subfolder
    (e.g., /path/Families/gen/[artifact]*.java).

    The function looks for Java files with the specified artifact ID in the gen folder.

    Args:
        package_path (Path): The path to the model package (e.g., /workspace/Families).
                             The function will look for Java files in package_path/gen/.
        artifact_id (str): The Maven artifact ID of the model (e.g., "Families").

    Returns:
        dict[Path, str]: A dictionary mapping each Java file path to its content.
    """
    gen_path = package_path / "gen" / artifact_id

    # If gen folder doesn't exist, try the package_path directly as fallback
    search_path = gen_path if gen_path.exists() and gen_path.is_dir() else package_path

    result = {}
    for java_file in search_path.glob("*.java"):
        result[java_file] = java_file.read_text()
    return result


# EMF dependencies for model modules (same as in prepare_workspace.py)
EMF_DEPENDENCIES: list[Dependency] = [
    Dependency(
        group_id="org.eclipse.emf",
        artifact_id="org.eclipse.emf.ecore",
        version="2.42.0",
    ),
    Dependency(
        group_id="org.eclipse.emf",
        artifact_id="org.eclipse.emf.common",
        version="2.42.0",
    ),
    Dependency(
        group_id="org.eclipse.emf",
        artifact_id="org.eclipse.emf.ecore.xmi",
        version="2.40.0",
    ),
]


def copy_model_to_workspace(
    workspace: Path,
    model_path: Path,
) -> MavenProject:
    """
    Copies a model package to the workspace and uses its existing pom.xml.

    The module name is derived from the model_path stem (e.g., "/path/to/Families" → "Families").
    The model package must already contain a valid pom.xml which will be used as-is.
    EMF dependencies are added if not already present.

    Args:
        workspace: The workspace directory (parent pom.xml location).
        model_path: The path to the model package to copy (must contain pom.xml).

    Returns:
        MavenProject: The loaded Maven project for the model module.

    Raises:
        FileNotFoundError: If the model_path does not contain a pom.xml.
    """
    parent = MavenProject.load(workspace)

    # Derive module name from model_path stem (last component of the path)
    module_name = model_path.stem

    # Create destination path in workspace
    dest_path = workspace / module_name

    # Check that source has a pom.xml
    source_pom_path = model_path / "pom.xml"
    if not source_pom_path.exists():
        raise FileNotFoundError(
            f"Model package at '{model_path}' does not contain a pom.xml. "
            "The model must be a valid Maven project with an existing pom.xml."
        )

    # Copy the model package to the workspace (including existing pom.xml)
    if dest_path.exists():
        shutil.rmtree(dest_path)
    shutil.copytree(model_path, dest_path)

    # Load the Maven project and add EMF dependencies if not already present
    project = MavenProject.load(dest_path)
    for dependency in EMF_DEPENDENCIES:
        project.pom.add_dependency(dependency)
    project.pom.save()

    # Register the new module with the parent
    MavenProject.register_submodule(parent, project)

    return project


def create_explore_models_node():
    async def explore_models(state: PreparationState) -> PreparationState:
        """
        Explores the folder structure of the source and target models. Each of them is a Java package generated by EMF.
        The function copies the model packages to the workspace, registers them as Maven modules, validates them,
        and reads the content of the source and target model files to return their implementations as strings.
        """
        workspace = state.get("workspace_path")
        if workspace is None:
            raise ValueError("Workspace path must be set in the state.")
        if not workspace.exists():
            raise ValueError(f"Workspace path '{workspace}' does not exist.")

        group_id = state.get("group_id")
        if group_id is None:
            raise ValueError("Group ID must be set in the state.")

        # Validate that parent pom.xml exists
        parent_pom_path = workspace / "pom.xml"
        if not parent_pom_path.exists():
            raise ValueError(f"Parent pom.xml not found at '{parent_pom_path}'.")

        maven_project_path = state.get("maven_project_path")
        if not maven_project_path or not maven_project_path.exists():
            raise ValueError(
                f"Maven project path '{maven_project_path}' does not exist or is not set in the state."
            )

        source_model: ModelImplementation = state.get("source_model")
        if source_model is None:
            raise ValueError("Source model must be set in the state.")
        source_model_path = source_model.get("path")
        if source_model_path is None:
            raise ValueError("Source model path must be set in the state.")
        elif not source_model_path.exists():
            raise ValueError(f"Source model path '{source_model_path}' does not exist.")
        elif not source_model_path.is_dir():
            raise ValueError(
                f"Source model path '{source_model_path}' is not a directory."
            )

        target_model: ModelImplementation = state.get("target_model")
        if target_model is None:
            raise ValueError("Target model must be set in the state.")
        target_model_path = target_model.get("path")
        if target_model_path is None:
            raise ValueError("Target model path must be set in the state.")
        elif not target_model_path.exists():
            raise ValueError(f"Target model path '{target_model_path}' does not exist.")
        elif not target_model_path.is_dir():
            raise ValueError(
                f"Target model path '{target_model_path}' is not a directory."
            )

        # Derive module names from model paths (e.g., /path/to/Families → "Families")
        source_module_name = source_model_path.stem
        target_module_name = target_model_path.stem

        # Copy source model to workspace and load Maven module
        source_model_project = copy_model_to_workspace(
            workspace=workspace,
            model_path=source_model_path,
        )

        # Copy target model to workspace and load Maven module
        target_model_project = copy_model_to_workspace(
            workspace=workspace,
            model_path=target_model_path,
        )

        # Register modules in parent pom.xml using derived names
        parent_pom = Pom(parent_pom_path)
        parent_pom.add_module(Module(artifact_id=source_module_name))
        parent_pom.add_module(Module(artifact_id=target_module_name))
        parent_pom.save()

        # Add modules as dependencies to the maven_project_path
        maven_project = MavenProject.load(maven_project_path)
        maven_project.pom.add_dependency(
            Dependency(
                group_id=group_id, artifact_id=source_module_name, version="1.0.0"
            )
        )
        maven_project.pom.add_dependency(
            Dependency(
                group_id=group_id, artifact_id=target_module_name, version="1.0.0"
            )
        )
        maven_project.pom.save()

        # Validate the Maven projects
        # Reload parent project to get updated modules
        parent_project = MavenProject.load(workspace)
        if not parent_project.validate():
            raise ValueError(
                f"Parent Maven project at '{workspace}' is not valid. "
                "Run 'mvn validate' for details."
            )
        if not source_model_project.validate():
            raise ValueError(
                f"Source model Maven project at '{source_model_project.workspace}' is not valid. "
                "Run 'mvn validate' for details."
            )
        if not target_model_project.validate():
            raise ValueError(
                f"Target model Maven project at '{target_model_project.workspace}' is not valid. "
                "Run 'mvn validate' for details."
            )

        # Read the implementations from the copied model packages
        src_impls = read_generated_emf_implementations(
            source_model_project.workspace, source_module_name
        )
        if len(src_impls) == 0:
            raise ValueError("No Java files found in source model path.")

        tgt_impls = read_generated_emf_implementations(
            target_model_project.workspace, target_module_name
        )
        if len(tgt_impls) == 0:
            raise ValueError("No Java files found in target model path.")

        source_implementation = "\n\n".join(
            f"{file}:\n{content}" for file, content in src_impls.items()
        )
        target_implementation = "\n\n".join(
            f"{file}:\n{content}" for file, content in tgt_impls.items()
        )

        return {
            "source_model": {
                "name": state["source_model"]["name"],
                "path": source_model_path,
                "implementation": source_implementation,
            },
            "target_model": {
                "name": state["target_model"]["name"],
                "path": target_model_path,
                "implementation": target_implementation,
            },
        }

    return explore_models
