from pathlib import Path
from typing import TypedDict

from mdeagent.comprehension.plan import TransformationPlan
from mdeagent.evaluation.types import EvaluationRun


class ModelImplementation(TypedDict):
    name: str  # The name of the model (e.g. Family, Person); Register and Factory classes are derived from this name (e.g. FamilyRegister, FamilyFactory)
    path: Path  # The path to the model package
    implementation: str | None  # Aggregate of all Java files in the model package including their file names; This has to be set by the explore_models node after reading the model package


class PreparationState(TypedDict):
    """The state of the preparation subgraph."""
    
    # === Direct copy of MDEAgentState ===
    workspace_path: Path        
    required_commands: list[str] # List of required commands to be available in the system PATH in order to run the agent properly

    # === Required (Set by user) ===
    group_id: str | None = None  # Maven groupId for the generated project
    artifact_id: str | None = None  # Maven artifactId for the generated project
    benchmarx_path: Path | None = None  # Path to the benchmarx tool in the workspace. If None, then BenchmarX will not executed!

    # === Generation ===
    transformation_plan: TransformationPlan | None = None
    source_model: ModelImplementation       # This representation will be set by the explore_models node after reading the source model package
    target_model: ModelImplementation       # This representation will be set by the explore_models node after reading the target model package
    bxtool_path: Path | None = None         # This file be generated by the preparation_node and used by the implementation_node.

    # === Evaluation ===
    latest_evaluation_runs: list[EvaluationRun]
