from pathlib import Path
from typing import Dict

from .state import PreparationState


def read_generated_emf_implementations(package_path: Path) -> Dict[Path, str]:
    """Reads the generated EMF implementations from the given package path.

    Args:
        package_path (Path): The path to the package containing the generated EMF implementations.

    Returns:
        Dict[Path, str]: A dictionary mapping each Java file path to its content.
    """
    result = {}
    for java_file in package_path.glob("*.java"):
        result[java_file] = java_file.read_text()
    return result


def create_explore_models_node():
    def explore_models(state: PreparationState):
        """
        Explores the folder structure of the source and target models. Each of them is a Java package generated by EMF. The function reads the content of the source and target model files and returns their implementations as strings.
        """
        source_model_path: Path = state.get("source_model_path")
        target_model_path: Path = state.get("target_model_path")

        if source_model_path is None or target_model_path is None:
            raise ValueError(
                "Source model path and target model path must be set in the state."
            )
        elif not source_model_path.exists():
            raise ValueError(f"Source model path '{source_model_path}' does not exist.")
        elif not source_model_path.is_dir():
            raise ValueError(
                f"Source model path '{source_model_path}' is not a directory."
            )
        elif not target_model_path.exists():
            raise ValueError(f"Target model path '{target_model_path}' does not exist.")
        elif not target_model_path.is_dir():
            raise ValueError(
                f"Target model path '{target_model_path}' is not a directory."
            )

        src_impls = read_generated_emf_implementations(source_model_path)
        if len(src_impls) == 0:
            raise ValueError("No Java files found in source model path.")

        tgt_impls = read_generated_emf_implementations(target_model_path)
        if len(tgt_impls) == 0:
            raise ValueError("No Java files found in target model path.")

        source_implementation = "\n\n".join(
            f"{file}:\n{content}" for file, content in src_impls.items()
        )
        target_implementation = "\n\n".join(
            f"{file}:\n{content}" for file, content in tgt_impls.items()
        )

        return {
            "source_model_implementation": source_implementation,
            "target_model_implementation": target_implementation,
        }

    return explore_models
